### ISSUE TITLE
Does not work well with Zle/surround key bindings

### ISSUE THREAD

**Issue by softmoth** [zsh-users/zsh-syntax-highlighting#520] opened 2018-06-17 19:52 UTC
The key bindings for [Zle/surround][] are broken when zsh-syntax-highlighting (or zsh-history-substring-search) is loaded.

[Zle/surround]: https://github.com/zsh-users/zsh/blob/master/Functions/Zle/surround

The recommended bindings (in comments at the top of the `surround` function) are:
```zsh
autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround
```

The first three, `cs`, `ds` and `ys` don't work if z-sy-h is loaded. Upon hitting the `s`, the terminal beeps and I'm in viins mode. What should happen is that I can type `cs"(` and the surrounding double quotes will change to parentheses, and I remain in vicmd mode.

**Comment by danielshahaf** [comment] 2020-03-17 04:37
Works fine in current master, so closing.  If you can still reproduce it, please reopen.

Sorry for the extremely late answer — I haven't seen this issue before now ☹

**Comment by dhleong** [comment] 2020-03-17 12:41
I can still reproduce it with this `.zshrc`:

```
bindkey -v

# faster <esc> key
export KEYTIMEOUT=1

# vim-surround emulation:
# NOTE: zsh-syntax-highlighting currently breaks these :(
autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -a cs change-surround
bindkey -a ds delete-surround
bindkey -a ys add-surround
bindkey -M visual S add-surround

source ~/g/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

Without `zsh-syntax-highlighting`, the surround bindings work just fine with `KEYTIMEOUT=1`, but when I add it suddenly the compound bindings break. `S` in visual mode still works, however.

**Comment by danielshahaf** [comment] 2020-03-17 13:01
1. It works if the KEYTIMEOUT setting is removed.
2. It works if the feature/redrawhook branch is merged.

**Comment by danielshahaf** [comment] 2020-03-17 13:15
3. It works if the multikey vicmd bindings are changed to single key.

Looking at the zsh source, KEYTIMEOUT is set by default to `40`, and there isn't any handling that would differ between that value and your value, so this seems to be a pure race condition.  Try using the feature/redrawhook branch (merge it into master if you prefer).

**Comment by dhleong** [comment] 2020-03-17 13:17
The `feature/redrawhook` branch does indeed seem to work for me, thanks!

**Closed** 2020-08-09 11:11 UTC
Labels: Bug, Upstream, performance, widget-wrapping
