### ISSUE TITLE
zsh crash when reload `~/.zshrc`

### ISSUE THREAD

**Issue by dozer47528** [zsh-users/zsh-syntax-highlighting#286] opened 2016-04-01 08:17 UTC
1. Open the Terminal
2. Run `source ~/.zshrc`
3. Process completed

![screen shot 2016-04-01 at 16 16 12](https://cloud.githubusercontent.com/assets/1676951/14201522/1eda8a9a-f825-11e5-9a08-73f61cc10b46.png)

**Comment by danielshahaf** [comment] 2016-04-01 08:50
What's the output of `echo $ZSH_VERSION $ZSH_HIGHLIGHT_VERSION $ZSH_HIGHLIGHT_REVISION`?

Does this happen if you do `zsh -f` and therein run `repeat 2 source /path/to/.../zsh-syntax-highlighting.zsh`?

**Comment by dozer47528** [comment] 2016-04-01 08:59
```
echo $ZSH_VERSION $ZSH_HIGHLIGHT_VERSION $ZSH_HIGHLIGHT_REVISION
5.0.8 0.5.0-dev HEAD
```

And it doesn't happen when I use `zsh -f`

Here is my plugins list:
extract z git git-extras git-flow gitignore mvn bundler bower gitfast github npm vagrant python pip pyenv docker zsh-autosuggestions zsh-completions zsh_reload brew brew-cask zsh-syntax-highlighting

**Comment by danielshahaf** [comment] 2016-04-01 09:39
Please provide a minimal reproduction recipe.  (That is: bisect your dotfiles down to a minimum that still reproduces the problem, and has as few external dependencies as possible.)

Does "[Process completed]" mean zsh exited with a segfault / bus error?  In this case, try zsh 5.2.

(I assume you understand what I'm asking, but ask if anything is unclear.)

**Comment by dozer47528** [comment] 2016-04-01 09:54
this my minimal `.zshrc` file can cause the problem:

```
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="ys"

plugins=(zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
```

There are some conflicts between `zsh-autosuggestions` and `zsh-syntax-highlighting`

And I try to manually reload this two plugins like this:
* `source zsh-autosuggestions.plugin.zsh` : nothing happens
`source zsh-syntax-highlighting.plugin.zsh` : crash

The `zsh-syntax-highlighting.plugin.zsh` plugin will cause the problem.

And my `zsh` is the newest version from Homebrew.

**Comment by danielshahaf** [comment] 2016-04-02 05:28
Could you run `set -x` before the second `source z-sy-h.zsh` command?  What's the last command before it aborts?

Do you use zsh 5.2?  It's not clear from what you said whether you use 5.0.8 or 5.2.

**Comment by KuoE0** [comment] 2016-04-19 17:13
I have the same problem! Here is my step to produce:

```
~% zsh
~% source ~/.zshrc
~% [1]    26129 segmentation fault  zsh
```

This is my `.zshrc`:

```zsh
source $HOME/.antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply
```

**Comment by danielshahaf** [comment] 2016-04-22 11:35
Diagnosis and proposed fixes in #294.

**Comment by danielshahaf** [comment] 2016-04-22 11:37
Related discussion in zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions/issues/126

**Comment by KuoE0** [comment] 2016-04-22 15:17
That's great!! And I also test the same config on Ubuntu 14.04. It works without crash. Hope this info help you. 👍

**Comment by danielshahaf** [comment] 2016-04-23 06:19
@KuoE0 to clarify: you use the same .zshrc on Ubuntu 14.04 and on OS X 10.10, and the crash reproduces only on the latter?  For reference, what version of zsh do you use on the former?

**Comment by KuoE0** [comment] 2016-04-23 17:10
Sorry for the unclear info. There is the zsh and system info following:

```
~% zsh --version
zsh 5.0.2 (x86_64-pc-linux-gnu)

~% cat /etc/linuxmint/info
RELEASE=17.2
CODENAME=rafaela
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17.2 Rafaela"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_rafaela_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_rafaela_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 17.2 Cinnamon 64-bit
```

**Comment by danielshahaf** [comment] 2016-05-04 23:53
I've proposed to zsh-autosuggestions a patch that fixes the problem: https://github.com/zsh-users/zsh-autosuggestions/issues/126#issuecomment-217041261

**Comment by danielshahaf** [comment] 2016-05-05 00:00
Setting labels: "Upstream" because the root problem is in z-asug (it blindly wraps a non-z-asug widget that wraps a z-asug widget) and "Bug" because of the segfault symptom.

**Comment by danielshahaf** [comment] 2016-05-05 00:40
I caught this in gdb earlier, the backtrace was a loop of:

```
_zsh_autosuggest_invoke_original_widget
_zsh_autosuggest_modify
_zsh_autosuggest_widget_modify
_zsh_autosuggest_bound_self-insert
_zsh_highlight_call_widget
_zsh_highlight_widget_self-insert
```

**Comment by JayXon** [comment] 2016-05-18 23:34
Is this the same issue? It does not crash, but I can't do anything.
![screenshot 2016-05-18 at 4 29 52 pm](https://cloud.githubusercontent.com/assets/1552641/15378167/f028bb34-1d15-11e6-98c7-483b7abf6c69.png)

**Comment by danielshahaf** [comment] 2016-05-19 16:54
> Is this the same issue? It does not crash, but I can't do anything.

That's plausible, see <https://github.com/zsh-users/zsh-autosuggestions/issues/126#issuecomment-217121315>.  Does the patch posted two comments above it fix your symptoms?  (If not, please open a new issue and we can debug further there.)

**Comment by JayXon** [comment] 2016-05-19 18:10
No it did not, opened #322

**Comment by danielshahaf** [comment] 2016-10-18 02:57
Note that you need to run `make` after applying https://github.com/zsh-users/zsh-autosuggestions/issues/126#issuecomment-217121315.

I assume you'll find that if you run apply that patch and `make`, the problem disappears...  the other option would be that we have two independent segfault bugs here, but Occam's razor says that's not the case.

**Comment by danielshahaf** [comment] 2016-10-19 14:14
Closing.  The known problem in z-asug has known workarounds.  No other problem was identified.

**Closed by danielshahaf** 2016-10-19 14:14 UTC
Labels: Bug, Upstream, widget-wrapping

**Comment by garrettmac** [comment] 2017-01-10 04:58
I added this to my `.zshrc`

```
if [[ $ZSH_EVAL_CONTEXT == 'file' ]]; then
	printf "autosuggestions loaded"
  source "./.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
  source "./.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi
```
 This fixed my terminal from crashing.

this if statement will only run when a new window is open and wont get triggered

**Comment by seagle0128** [comment] 2017-01-14 19:59
Appear again on macOS Sierra

```shell
~ echo $ZSH_VERSION; echo $ZSH_HIGHLIGHT_VERSION; echo $ZSH_HIGHLIGHT_REVISION           
5.2
0.6.0-dev
HEAD
```

**Comment by popstas** [comment] 2017-03-05 20:33
@garrettmac, i think that need for sourcing when load from compiled .zwc, in my case:
```
if [[ $ZSH_EVAL_CONTEXT == 'file' ]] || [[ $ZSH_EVAL_CONTEXT == 'filecode' ]]; then
    source "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi
```

**Comment by danielshahaf** [comment] 2017-03-05 20:44
@popstas How about `if (( ZSHRC_LOAD_ONCE++ == 0 )); then source …; fi`?  No need to declare $LOADED_ONCE either before or after.

**Comment by danielshahaf** [comment] 2017-03-05 20:45
zsh-users/zsh-autosuggestions#126 has been fixed on zsh-autosuggestions' `develop` branch; anyone still seeing issues please update z-asug.  Thanks.

**Comment by popstas** [comment] 2017-03-05 20:53
@danielshahaf , thank you, your workaround nicer! Will watching for zsh-autosuggestions releases.
