### ISSUE TITLE
Causing segfault on Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by hotpxl** [zsh-users/zsh-syntax-highlighting#254] opened 2015-12-31 06:53 UTC
Reproduction

---

I created a new Ubuntu 14.04 x64 instance. Installed `zsh` and this plugin alongside prezto. And found out [this line](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/highlighters/main/main-highlighter.zsh#L64) would cause a segfault. Commenting out this line solves the problem.

**Comment by danielshahaf** [comment] 2015-12-31 09:19
Thanks for narrowing it down to a single line.  (Incidentally, that line is an `||` statement, so it's not clear whether you commented out the entire statement or only the first disjunct; but read on before checking that.)

Ubuntu 14.04 has zsh-5.0.2.  Could you try zsh-5.2?

Does the error reproduce under `zsh -f` followed by `source zsh-syntax-highlighting.zsh`?  (This removes prezto, OS dotfiles, and your personal dotfiles from the equation.)

**Comment by hotpxl** [comment] 2016-01-02 09:56
1. Only the first disjunct.
1. There is no problem under `zsh -f` and `source ...`. Looks like it's conflicting with something else in prezto.

I'll try zsh-5.2 later. It requires compiling myself.

**Comment by hotpxl** [comment] 2016-01-02 10:02
```
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -61,6 +61,9 @@
 _zsh_highlight_main_highlighter_predicate()
 {
   # accept-* may trigger removal of path_prefix highlighting
+  echo "start"
+  echo $WIDGET
+  echo "end"
   [[ $WIDGET == accept-* ]] ||
     _zsh_highlight_buffer_modified
 }
```

I tried printing the variable. The shell could output `start` and `zle-line-init` but not `end`. Looks like it somehow triggers the segmentation fault after accessing the `$WIDGET` variable.

**Comment by hotpxl** [comment] 2016-01-02 10:19
The problem does not exist on Zsh 5.2.

**Comment by danielshahaf** [comment] 2016-01-02 12:33
Thanks for the additional information, @hotpxl.  I suggest you follow up with prezto to isolate the bug and implement a workaround for zsh ≤ 5.1.1.  I'm closing this issue since it seems no z-sy-h changes will be required, but do feel free to reopen it should changes in z-sy-h be needed.

**Closed by danielshahaf** 2016-01-02 12:33 UTC
Labels: Question
