### ISSUE TITLE
Not working with oh-my-zsh

### ISSUE THREAD

**Issue by seemsindie** [zsh-users/zsh-syntax-highlighting#270] opened 2016-01-28 13:13 UTC
I may be an idiot, but i tried everything, but it doesn't work...

I cloned it into custom plugins under oh-my-zsh, i added this to plugins:

    zsh-syntax-highlighting

I even added this to end of .zshrc:

    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor line root)

But i still don't see thing highlighted 
![image](https://cloud.githubusercontent.com/assets/1268576/12645265/2de64224-c5c9-11e5-80e6-457bbd74c5b7.png)

Any idea what am i missing?

Thanks.

**Comment by danielshahaf** [comment] 2016-01-28 18:41
Is z-sy-h the _last_ plugin listed?

Why is the word ".zshrc" green, do you have a plugin that colors the entire command-line green?

Do you get highlighting if you run `zsh -f` followed by `source .../zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`?

**Comment by jazen** [comment] 2016-02-26 10:36
@danielshahaf Same problem here but `zsh -f` and sourcing it manually does work..

**Comment by danielshahaf** [comment] 2016-03-01 21:08
@jazen If it works in `zsh -f` and not otherwise, then (a) try in `zsh -d`, (b) binary-search your `.z*` dotfiles (and in particular your `$plugins` array) until you have a minimal config that reproduces the problem.

**Comment by jazen** [comment] 2016-03-02 09:16
@danielshahaf What i found is that it stops working when setting `$ZSH_CUSTOM=$HOME/.zsh.d` — Doesn't matter whether the directory exists, is given as absolute path or whatever.. the simple use of `$ZSH_CUSTOM` seems to prevent it from working!?

**Comment by danielshahaf** [comment] 2016-03-02 10:40
@jazen `$ZSH_CUSTOM` is an oh-my-zsh knob; neither zsh upstream nor z-sy-h use it in any way.  Since you stated z-sy-h does work when sourced directly, the problem must be with the omz glue code that finds and loads z-sy-h.  I therefore suggest you forward this question to the omz folks.  (Sorry to bounce you around, of course; if I had a fix I'd have posted it.)

In the meantime, to get things working, you can install z-sy-h in the "without omz" way (by running `source .../zsh-syntax-highlighting.zsh` in `.zshrc` after all widgets have been defined).

[z-sy-h's installation docs](INSTALL.md#with-oh-my-zsh) don't mention $ZSH_CUSTOM.  Does that doc need to be extended or clarified?

**Comment by apjanke** [comment] 2016-03-04 20:20
> z-sy-h's installation docs don't mention $ZSH_CUSTOM. Does that doc need to be extended or clarified?

Probably. `$ZSH_CUSTOM` defines the location of your Oh My Zsh custom directory; `~/.oh-my-zsh/custom` is just its default. The `INSTALL.md` instructions say to install it to `~/.oh-my-zsh/custom`.

```
1. Clone this repository in oh-my-zsh's plugins directory:

        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
```

The path `~/.oh-my-zsh/custom` (or, rather, `$ZSH/custom`) is just the default value of `$ZSH_CUSTOM`. If you have `$ZSH` or `$ZSH_CUSTOM` set to something else, then OMZ will be looking in that other location for custom-installed plugins, and won't see your z-sy-h installation at `~/.oh-my-zsh/custom`. And when OMZ's initialization code sees an unrecognized plugin in `$plugins`, it silently ignores it, so the error may not be obvious to users.

@seemsindie: What are your values of `$ZSH` and `$ZSH_CUSTOM`, and where did you install z-sy-h?

You can run `zsh -l -x` to enable tracing of your startup sequence. It'll be very verbose but will let you verify whether the plugins are being loaded. Or just stick debugging `echo`s in `$ZSH/oh-my-zsh.sh`.

**Comment by danielshahaf** [comment] 2016-03-05 12:40
> The path `~/.oh-my-zsh/custom` (or, rather, `$ZSH/custom`) is just the default value of `$ZSH_CUSTOM`.

Should the installation instructions line be changed to: `git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting` ?

> And when OMZ's initialization code sees an unrecognized plugin in `$plugins`, it silently ignores it, so the error may not be obvious to users.

Perhaps omz upstream should change this behaviour, then.

**Comment by danielshahaf** [comment] 2016-03-12 18:35
No comments in a week, so closing; feel free to reopen if needed.  Thanks again for the hint Andrew.

**Closed** 2016-03-12 18:37 UTC
Labels: Question

**Comment by jazen** [comment] 2016-03-17 18:56
@danielshahaf  Thanks :+1:

**Comment by nharward-hd** [comment] 2016-09-21 22:48
Same problem on ArchLinux (zsh=5.2, zsh-syntax-highlighting=0.4.1). I noticed in the `-l -x` output (thanks @apjanke for the suggestion) that oh-my-zsh is looking for a file named `zsh-syntax-highlighting.plugin.zsh` but the file in the zsh-syntax-highlighting plugin folder is missing the `.plugin` part of the name - it's just `zsh-syntax-highlighting.zsh`. Looks like a file with the expected name was added to the git repo shortly before this issue was opened. In this case the upstream changes just haven't made it to my distro yet but explains why the git clone solution works correctly.

Just wanted to post the root cause so people can +1 their package maintainers to update for their distros.

**Comment by danielshahaf** [comment] 2016-09-21 23:56
> Looks like a file with the expected name was added to the git repo shortly before this issue was opened. In this case the upstream changes just haven't made it to my distro yet but explains why the git clone solution works correctly.

Well, not quite.  A *.plugin.zsh file has always existed; the recent change was to convert that file from a symlink to a plain file.

Note that `make install` does not install the *.plugin.zsh file.  That's because the various plugin managers (oh-my-zsh included) usually clone z-sy-h's git master.  I don't use a plugin manager myself, but if it's possible to point a plugin manager at /usr/local/share/zsh-syntax-highlighting/, then perhaps `make install` should install the .plugin.zsh file too.

Thanks for the additional information @nharward-hd.

**Comment by Lmasters754** [comment] 2019-03-13 19:48
> Is z-sy-h the _last_ plugin listed?
> 
> Why is the word ".zshrc" green, do you have a plugin that colors the entire command-line green?
> 
> Do you get highlighting if you run `zsh -f` followed by `source .../zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`?

It works for me.. thank U!

**Comment by Rockin4Life33** [comment] 2020-05-14 17:46
> [z-sy-h's installation docs](INSTALL.md#with-oh-my-zsh) don't mention $ZSH_CUSTOM. Does that doc need to be extended or clarified?

Bad link: Try [zsh-syntax-highlighting install docs](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md)

**Comment by danielshahaf** [comment] 2020-05-15 06:42
Thanks, fixed.
