### ISSUE TITLE
tmux panes die upon creation

### ISSUE THREAD

**Issue by felixSchl** [zsh-users/zsh-syntax-highlighting#276] opened 2016-03-08 18:31 UTC
When I source the syntax highlighting script in my `.zshrc`, and then launch tmux and create panes, either the newly created pane or previously created panes immediately die.

I have reported the issue on two zsh plugin manager repos, thinking the problem was there:

* https://github.com/tarjoilija/zgen/issues/53
* https://github.com/b4b4r07/zplug/issues/35

But after looking into it, I found that it has to do with loading the syntax highlighting script. As soon as I place `source ~/.zplug/repos/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh` in my `.zshrc`, the behaviour occurs.

This issue seems to only occur on OSX, as I was unable to reproduce the issue in docker. I am using iterm2/3, and `zsh 5.1.1 (x86_64-apple-darwin13.4.0)` and tried both tmux 1.9 and 2.1. I have tried on operating systems Mavericks and Yosemite.

**Comment by phy1729** [comment] 2016-03-08 18:54
I can't reproduce this with tmux 2.1 on OSX 10.11.3 (zsh 5.2) or 10.9.5 (zsh 5.0.2 and 5.2) with a .tumx.conf of

    set -g default-command "zsh -f"

and the steps

1. Start tmux
2. Create a new pane
3. Source zsh-syntax-highlighting.zsh

Am I missing a step?

**Comment by felixSchl** [comment] 2016-03-08 19:22
Alright, I have done a bit more dissecting. The problem seems to appear only when using zsh-syntax-highlighting in conjunction with [vi-mode](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/vi-mode). This should reproduce it:

```sh
source ~/robbyrussell/oh-my-zsh/plugins/vi-mode/vi-mode.plugin.zsh
source ~/zsh-users/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

**Comment by danielshahaf** [comment] 2016-03-09 16:26
Could you `set-option -g set-remain-on-exit on` and see if you get an error message?  Can you try zsh 5.2 (it sounds like zsh is exiting prematurely)?

**Comment by felixSchl** [comment] 2016-03-09 18:02
Alright, all i get is "Pane is dead" in the lower right corner. Actually, it shows though that it's not the new pane that is dying, but always the previous one.

**Comment by felixSchl** [comment] 2016-03-09 18:07
Same behaviour with zsh 5.2 (`zsh 5.2 (x86_64-apple-darwin13.4.0)`)

**Comment by felixSchl** [comment] 2016-03-09 18:14
Alright, seems that if you comment out [L7-L10](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/vi-mode/vi-mode.plugin.zsh#L7-L10) of the vi-mode scripts, it all works.

**Comment by danielshahaf** [comment] 2016-03-09 18:19
I edited your link to avoid bitrot (see http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=37966).  Can you change that `zle reset-prompt` to `zle .reset-prompt` (with the dot) and try again?

I don't recall whether there were any relevant changes in master post 5.2.

**Comment by felixSchl** [comment] 2016-03-09 18:21
> I edited your link to avoid bitrot 

I was just editing my comment to do the same, after I noticed.

Using `setopt XTRACE VERBOSE` on top of my `.zshrc`, I can see what's happening a bit clearer: When I create a second pane, the previous one receives the window sized change signal and executes the aforementioned lines, or in particular: `zle && { zle reset-prompt; zle -R }` and then it crashes. I feel like I have to take this issue to their repo now, but I have already filed an issue for this in two other projects... :/

**Comment by felixSchl** [comment] 2016-03-09 18:23
> Can you change that `zle reset-prompt` to `zle .reset-prompt` (with the dot) and try again?

that works!!

**Comment by felixSchl** [comment] 2016-03-09 18:25
Do you want to create a pull request at their repo? I would not want to take your credit. Could you reference this issue, and also:

* https://github.com/tarjoilija/zgen/issues/53
* https://github.com/b4b4r07/zplug/issues/35

please? Alternatively I can do this for you and give you attribution in the commit and the PR?

**Comment by danielshahaf** [comment] 2016-03-09 18:50
> Do you want to create a pull request at their repo?

Hold your horses :-)  I only asked you to make that change in order to determine whether the trigger to the bug was in z-sy-h's code or elsewhere; I'm not sure yet whether it's a correct change for vi-mode upstream to make.  (Adding the dot bypasses z-sy-h for that one widget invocation.)

To debug it further, you can run `functions -t ${widgets[reset-prompt]#user:}` after loading z-sy-h, which will print a line-by-line trace to stderr, so we can see what's the last line run before zsh crashes.  (This is similar to the xtrace option.)

Can you easily test zsh from master?  (Clone https://github.com/zsh-users/zsh/, build/run it as `Util/preconfig && ./configure --enable-zsh-debug && make && Src/zsh -f`.)  I'm trying to rule out the possibility that it's a zsh upstream bug that has been fixed in zsh 5.3-dev-1.

Could you check what error code zsh dies with?  You ought to be able to get that by using /bin/sh as your shell in tmux, running zsh within that, starting a new pane, and then `echo $?` after zsh dies.

P.S. On my system, `${widgets[reset-prompt]#user:}` is `_zsh_highlight_widget_reset-prompt`.

**Comment by danielshahaf** [comment] 2016-03-09 19:05
By the way, setting TRAPWINCH in a plugin (like vi-mode does) isn't a great idea: if the user's .zshrc or another plugin also define a WINCH trap, vi-mode's trap would be overridden.

I guess the right fix would be to develop some sort of $sigwinch_functions array, like [$precmd_functions](http://zsh.sourceforge.net/Doc/Release/Functions.html#Hook-Functions), to allow multiple subscriptions.  (See also [add-zsh-hook](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Manipulating-Hook-Functions).)

Feel free to point this out to the vi-mode developers.  (I don't use that plugin myself.)

**Comment by felixSchl** [comment] 2016-03-10 20:29
Alright, I will set some time aside this weekend to run through the steps above. I doubt I'll get to it today.

**Comment by felixSchl** [comment] 2016-03-13 04:19
Strange, I cannot repro at home at all with the same set up as above.. This bug is getting the best of me.

**Comment by danielshahaf** [comment] 2016-03-13 17:20
Then try following those steps on the one computer that does reproduce the problem :-).  Also, compare the dependencies between the reproducing and non-reproducing setups (from patches to zsh itself up to and including kernel versions, since signals are involved), and figure out whether the problem might be local to just one machine for some reason.

**Comment by felixSchl** [comment] 2016-03-30 18:55
I won't be looking into this any further. Should anyone else be tripped up by this, I think there's enough of a bread trail to follow and find this thread (or so I hope). If you think that the dot in front of reset-prompt is a somewhat acceptable (despite not perfect) solution that could be suggested over in the vi-mode repo, I'd be glad to suggest it there. Feel free to close this issue.

**Comment by danielshahaf** [comment] 2016-04-01 13:22
@felixSchl Thanks for following up.  Closing as you suggested.  If you or anyone else runs into this issue in the future, feel free to reopen or to file a new issue.

**Closed by danielshahaf** 2016-04-01 13:22 UTC

**Comment by nadeemahmad** [comment] 2016-06-06 01:23
I have seen something similar to this. For details, see <https://github.com/zsh-users/zsh-autosuggestions/issues/166>.
