### ISSUE TITLE
Highlights red after  path autocompletion

### ISSUE THREAD

**Issue by RegreTTO** [zsh-users/zsh-syntax-highlighting#912] opened 2023-01-08 15:30 UTC
When I type some path beginning it is highlighted by red as it should be, but after I use autocomplete, typed part is still red while the rest part of the path is highlighted  normally

![изображение](https://user-images.githubusercontent.com/39791198/211204952-54ff4d70-a35b-4fa8-ab57-d44de8022879.png)

In this example I've typed ` ~/.oh-my-zsh/` manually and then invoked autocomplete

**Comment by phy1729** [comment] 2023-01-08 16:00
My best guess would be autocomplete is sourced after z-sy-h, so z-sy-h can't wrap that key bind. Please double check the order plugins are sourced.

**Comment by RegreTTO** [comment] 2023-01-08 17:02
I've put this plugin on the top of the others, but it hasn't helped

**Comment by RegreTTO** [comment] 2023-01-08 17:06
This is a part from my `.zshrc`
```
# ZSH Highlighting settings
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[path]='underline, standout'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#65c7c4, bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=#65c7c4, bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#65c7c4, bold'

ZSH_THEME="bira"
plugins=(
  zsh-syntax-highlighting
  git
  gitignore
  zsh-autosuggestions
  virtualenv
  copyfile
  interactive-cd
  z
)
```

**Comment by phy1729** [comment] 2023-01-08 17:07
z-sy-h should be last not first. See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh

**Comment by RegreTTO** [comment] 2023-01-08 17:14
Unfortunatelly after moving it down nothing's changed

**Comment by AndreasBackx** [comment] 2023-01-25 10:06
I have a similar issue, when typing `sud`, the `zsh-autosuggestions` plugin suggests my last command which is `sudo dnf install difftastic`:

![image](https://user-images.githubusercontent.com/1593486/214534052-82edf09a-a6ea-4333-8944-b7a8115fde3e.png)

When pressing the right arrow to autocomplete it, completes it properly but the syntax highlighting is incorrect:

![image](https://user-images.githubusercontent.com/1593486/214534334-d69f2bb2-45e7-430d-b818-ef6ba9679cbd.png)

Meanwhile while typing it manually in its entirety does show it properly:

![image](https://user-images.githubusercontent.com/1593486/214534451-e0b9e344-43f8-459a-92dc-82cc5b05c245.png)

Pressing the right arrow shows where you pressed it if you do it midway through:

![image](https://user-images.githubusercontent.com/1593486/214534516-9c99ef6b-e45e-4f0f-b406-1cc0b3f6d94a.png)

My dotfiles are here: https://github.com/AndreasBackx/dotfiles. In my latest commit as of writing I move the plugin to the end, but that does not seem to make a difference. If I can help make a reproducible sample, I would love to try but don't know how right now. I have this problem on at least 2 machines, perhaps 3. Definitely 1 Fedora 37 and 1 Arch Linux machine, possibly 1 other Fedora 37 machine that I cannot test right now.

- `uname -a`: `Linux andreasbackx-fedora-S4PE2053 6.1.7-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 18 17:11:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- `zsh --version`: zsh 5.9 (x86_64-redhat-linux-gnu)
- `oh-my-zsh` and all plugins are the latest version as of writing.

Let me know if there's something else I can provide.

**Comment by danielshahaf** [comment] 2023-01-25 10:26
> If I can help make a reproducible sample, I would love to try but don't know how right now.

In short: run `zsh -f` and therein: use the `source` builtin to load the relevant plugins (as few as possible, of course); run `echo` or `true` or `:` with some arguments to populate history; type another command (and possibly press [Tab] or [→] or whatever) to reproduce the problem.  Also, include the commit hashes of everything, don't just say "latest".  Thanks :)

**Comment by gashnya** [comment] 2023-01-29 17:04
Same problem after upgrading from Ubuntu 22.04 to 22.10.

- **Ubuntu** 22.10 5.19.0-29-generic
- **zsh** 5.9 (x86_64-ubuntu-linux-gnu)
- **zsh-autosuggestion** [a411ef3](https://github.com/zsh-users/zsh-autosuggestions/commit/a411ef3e0992d4839f0732ebeb9823024afaaaa8)
- **colorize** [138132f](https://github.com/zpm-zsh/colorize/commit/138132f681bc429dcae3840cca580da9f860cf0b)
- **zsh-command-not-found** [cd0e82c](https://github.com/Tarrasch/zsh-command-not-found/commit/cd0e82cf24596df333dcbbe4b414efe99c9fe9b7)
- **zsh-syntax-highlighting** [b2c910a](https://github.com/zsh-users/zsh-syntax-highlighting/commit/b2c910a85ed84cb7e5108e7cb3406a2e825a858f)

As @danielshahaf suggested, I tried to sequentially source plugins in no-rcs mode and check at every step if the problem appears:

```
zhenya% source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
zhenya% source ~/.zsh/colorize/colorize.plugin.zsh
zhenya% source ~/.zsh/zsh-command-not-found/command-not-found.plugin.zsh
zhenya% source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
```

At this point everything works as it worked before (I suppose, the right color for suggestions is grabbed from my terminal colors). 

![Screenshot_2023-01-29_19-43-27](https://user-images.githubusercontent.com/79607890/215341106-399330ad-35fd-4933-b0b2-24e5ad26e1e2.png)
![Screenshot_2023-01-29_19-44-10](https://user-images.githubusercontent.com/79607890/215341112-5af33ea0-7c0d-434a-a19f-7f6454fe45ba.png)

So, I tried another line from my `.zshrc`:

```bash
zhenya% ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#7F7864'
```

After that, accepted suggestions began to be highlighted incorrectly. 

![Screenshot_2023-01-29_19-44-56](https://user-images.githubusercontent.com/79607890/215341132-137de9b2-5452-4b88-bed0-4c09c701da32.png)
![Screenshot_2023-01-29_19-45-20](https://user-images.githubusercontent.com/79607890/215341138-59c3390c-1e21-4d6d-a285-0c185555cae9.png)


Removing this line from `.zshrc` solved the problem for me. But, interestingly, setting another color also corrects highlighting:

```bash
zhenya% ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#777777'
```
![Screenshot_2023-01-29_19-47-15](https://user-images.githubusercontent.com/79607890/215341256-b9cc3bdd-86e9-406d-8431-a2b1055f6665.png)
![Screenshot_2023-01-29_19-48-18](https://user-images.githubusercontent.com/79607890/215341258-77356889-763e-457f-ab2b-18bfe2082cc7.png)

Additionally, I noticed that everything works fine with hex colors without letters. Hope, this will be useful for somebody.

**Comment by AndreasBackx** [comment] 2023-01-30 23:25
> In short: run `zsh -f` and therein: use the `source` builtin to load the relevant plugins (as few as possible, of course); run `echo` or `true` or `:` with some arguments to populate history; type another command (and possibly press [Tab] or [→] or whatever) to reproduce the problem. Also, include the commit hashes of everything, don't just say "latest". Thanks :)

@danielshahaf

* zsh-syntax-highlighting: b2c910a85ed84cb7e5108e7cb3406a2e825a858f
* zsh-autosuggestions: a411ef3e0992d4839f0732ebeb9823024afaaaa8
* oh-my-zsh: b2313ec7493dc127c9712f20654579221d0bcce6

So running `zsh -f` I can reproduce it as follows:

```
$ plugins=(zsh-autosuggestions zsh-syntax-highlighting)
$ source $HOME/.oh-my-zsh/oh-my-zsh.sh
$ echo 1
```

Then typing `echo` and right arrow will lead to the bug.

![image](https://user-images.githubusercontent.com/1593486/215618350-76d87e53-224e-4648-83b2-717b20b33beb.png)

Without oh-my-zsh and sourcing the files directly also leads to the problem so it seems to be unrelated to oh-my-zsh?

![image](https://user-images.githubusercontent.com/1593486/215618656-4ae05782-c36b-45e9-9333-0da3974dc2b0.png)

What @gashnya says I can reproduce as well.

![image](https://user-images.githubusercontent.com/1593486/215619025-4cb519f2-cbcc-4b39-8451-a8852953bde8.png)

Thus if I set it to my default, it fixed it for me.

![image](https://user-images.githubusercontent.com/1593486/215619544-f579ce44-53a0-4a98-a0cc-047a5b5fe731.png)

**Comment by AndreasBackx** [comment] 2023-01-30 23:32
Just after writing this previous comment I noticed that I have the following in my dotfiles:

```
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=0"
```

Turns out that was the problem for me. Just removing that fixes the problem.

It turns out that setting that explicitly makes for the bug...

It does so for explicit colour numbers:

![image](https://user-images.githubusercontent.com/1593486/215620022-8f9080c4-0d03-4af4-a33e-74d31135565c.png)

And for hex codes:

![image](https://user-images.githubusercontent.com/1593486/215620340-dcbe0d0c-203b-4f0c-998c-e1d2d0deb043.png)

Fixed it in my dotfiles here: https://github.com/AndreasBackx/dotfiles/commit/4c14884a9f5b5d4297f52bfe898f7a7ce77b0c97

**Comment by danielshahaf** [comment] 2023-02-02 15:25
Thanks for the additional information.

I'd like to repeat that I requested _minimal_ reproduction recipes, involving _as few external dependencies as possible_.  That means one external plugin is better than three, and without omz is better than with.

Anyway, I can reproduce this now using

- zsh 5.9
- z-sy-h caa749d030d2
- z-asug a411ef3e0992

To reproduce:

```zsh
$ zsh-5.9 -f
% bindkey -e
% . ./asug
% . ./zsyh
% ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#FF00FF'
% echo true
true
% echo «press Ctrl+E»
true
```

Note that this only reproduces with uppercase hex digits (!).  With lowercase hex digits it's fine.

**Comment by danielshahaf** [comment] 2023-02-02 15:26
"Reproduces" means that the stuff added by the press of Ctrl+E is in #FF00FF rather than in whatever colour z-sy-h would have it.

**Comment by danielshahaf** [comment] 2023-02-02 15:35
Duplicate of https://github.com/zsh-users/zsh-autosuggestions/issues/698; see Oliver's comments there for the recommended solution (tl;dr z-asug should use the `memo=` feature of zsh≥5.9).

To be clear, this isn't a bug in z-sy-h.

**Closed by danielshahaf** 2023-02-02 15:35 UTC
