### ISSUE TITLE
Error when using `zsh-syntax-hightlighting` with `zaw`

### ISSUE THREAD

**Issue by magthe** [zsh-users/zsh-syntax-highlighting#500] opened 2018-01-26 09:28 UTC
When using the following configuration (`~/.zshrc`):

```
HISTSIZE=5000
SAVEHIST=2500
HISTFILE=~/.zhist
source ~/.zplug/init.zsh
zstyle :filter-select hist-find-no-dups yes
zplug zsh-users/zaw
zplug zsh-users/zsh-syntax-highlighting, defer:2
zplug load
bindkey '^R' zaw-history
```

and I do the following:

1. Press CTRL-R to open `zaw`'s interactive history search
2. Press enter on the first history item to run it

I get the following error:

```
_zsh_highlight:17: bad set of key/value pairs for associative array
```

If I remove the line `zstyle :filter-select hist-find-no-dups yes` from my configuration the error message stops appearing.

**Comment by magthe** [comment] 2018-01-26 09:30
Since I don't know which plugin is at fault I've raised the same issue in both projects. See zsh-users/zaw#93

**Comment by danielshahaf** [comment] 2018-01-26 11:51
Thanks for cross-referencing.

The cause is that zaw creates a variable named `options`, hiding the variable of the same provided by zsh itself via a standard module.

**Comment by danielshahaf** [comment] 2018-01-26 15:22
zaw will rename the offending variable (see discussion on the zaw issue).  That leaves three questions, two for upstream:

- Should zsh upstream expose its variable not only as $options but also as $zsh_options so (in the long term) scripts can transition to the latter name, which is less likely to clash?
- Should zsh upstream make it harder to hide special variables such as $options?  (E.g., by not implicitly setting the `-h` typeset attribute on zsh/parameter special parameters (as documented under the `-h` flag to the `typeset` builtin)?

and one for us:

- Is any change needed on z-sy-h's side?

**Comment by danielshahaf** [comment] 2018-01-26 15:25
Once we switch to zle-line-pre-redraw -based highlighting, this probably won't be an issue, either.

**Comment by danielshahaf** [comment] 2018-01-26 15:49
Closing as inactionable. Cheers!

**Closed by danielshahaf** 2018-01-26 15:49 UTC
Labels: Upstream, widget-wrapping
