### ISSUE TITLE
syntax highlighting breaks if no completion is available

### ISSUE THREAD

**Issue by xuhdev** [zsh-users/zsh-syntax-highlighting#113] opened 2013-06-01 23:25 UTC
For example,

    mkdir tmp
    cd tmp
    ls # then hit <TAB>

You will find the color `ls` becomes the standard color, instead of keeping what it was.

**Comment by danielshahaf** [comment] 2015-09-05 18:47
The following patch (against 546a5288e243c3fabd98fc1a4d60165fa2a257a9) fixes it:

```
diff --git a/zsh-syntax-highlighting.zsh b/zsh-syntax-highlighting.zsh
index e418187..f0ad80f 100644
--- a/zsh-syntax-highlighting.zsh
+++ b/zsh-syntax-highlighting.zsh
@@ -147,16 +147,16 @@ _zsh_highlight_bind_widgets()
 
       # User defined widget: override and rebind old one with prefix "orig-".
       user:*) eval "zle -N orig-$cur_widget ${widgets[$cur_widget]#*:}; \
-                    _zsh_highlight_widget_$cur_widget() { builtin zle orig-$cur_widget -- \"\$@\" && _zsh_highlight }; \
+                    _zsh_highlight_widget_$cur_widget() { builtin zle orig-$cur_widget -- \"\$@\"; _zsh_highlight }; \
                     zle -N $cur_widget _zsh_highlight_widget_$cur_widget";;
 
       # Completion widget: override and rebind old one with prefix "orig-".
       completion:*) eval "zle -C orig-$cur_widget ${${widgets[$cur_widget]#*:}/:/ }; \
-                          _zsh_highlight_widget_$cur_widget() { builtin zle orig-$cur_widget -- \"\$@\" && _zsh_highlight }; \
+                          _zsh_highlight_widget_$cur_widget() { builtin zle orig-$cur_widget -- \"\$@\"; _zsh_highlight }; \
                           zle -N $cur_widget _zsh_highlight_widget_$cur_widget";;
 
       # Builtin widget: override and make it call the builtin ".widget".
-      builtin) eval "_zsh_highlight_widget_$cur_widget() { builtin zle .$cur_widget -- \"\$@\" && _zsh_highlight }; \
+      builtin) eval "_zsh_highlight_widget_$cur_widget() { builtin zle .$cur_widget -- \"\$@\"; _zsh_highlight }; \
                      zle -N $cur_widget _zsh_highlight_widget_$cur_widget";;
 
       # Default: unhandled case.
```

But I'm not sure the patch is correct: it might mask legitimate errors, too.

**Comment by danielshahaf** [comment] 2015-09-06 18:55
Duplicate of issue #90.

**Closed by danielshahaf** 2015-09-06 18:55 UTC
Labels: Bug
