### ISSUE TITLE
Single hyphen option highlighted incorrectly

### ISSUE THREAD

**Issue by jcrd** [zsh-users/zsh-syntax-highlighting#559] opened 2018-10-20 21:02 UTC
As of commit e27e53b some single hyphen options are highlighted with unknown-token.

![image](https://user-images.githubusercontent.com/44040597/47260399-2c591600-d478-11e8-900f-0e903195fc44.png)

**Comment by phy1729** [comment] 2018-10-20 21:06
I can't reproduce this, Is pacman aliased to `sudo pacman` in which case does #556 fix the issue?

**Comment by jcrd** [comment] 2018-10-20 21:16
Yes, pacman is aliased to `sudo pacman` and #556 does fix this issue.

**Comment by danielshahaf** [comment] 2018-10-21 02:33
#556 has been merged.

**Closed by danielshahaf** 2018-10-21 02:33 UTC
