### ISSUE TITLE
No highlighting while cycling menu completion results

### ISSUE THREAD

**Issue by m0vie** [zsh-users/zsh-syntax-highlighting#375] opened 2016-09-27 22:28 UTC
While cycling through results in menu completion, no highlighting is applied:
![untitled](https://cloud.githubusercontent.com/assets/1491108/18894288/5b14e33c-8512-11e6-9c57-b0459eac6c66.png)

1) No widget is called for current `master` branch.

2) `zle-line-pre-redraw` is not called, either.

Not sure about 1), but 2) can probably be fixed by introducing another `redrawhook();` in upstream.

**Comment by danielshahaf** [comment] 2016-10-16 15:33
Patch upstream: [workers/39590](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=39590)

**Comment by danielshahaf** [comment] 2016-10-19 14:49
Committed upstream in zsh-users/zsh@5b192a4cd1fafde42fcbc9b19cee40885705880e.  @m0vie, I assume we can close this issue, unless there is a z-sy-h side fix that can be done to support older zsh's?

**Comment by danielshahaf** [comment] 2016-10-19 14:50
(To be clear: the upstream patch fixes this issue.)

**Comment by m0vie** [comment] 2016-10-19 19:34
Yes, I don't think there is anything we can do to make it work with older versions.

**Comment by ratheesh** [comment] 2017-06-01 08:30
I still observe this issue in zsh v.5.3.1. Can somebody confirm if this is fixed in latest zsh.

**Comment by danielshahaf** [comment] 2017-06-01 13:16
@ratheesh Yes.

**Comment by ratheesh** [comment] 2017-06-02 17:06
If I enable menu select using
`zstyle ':completion:*:*:*:*:*' menu select`,
the functionality breaks. Is this expected?
Is there a setting or workaround to get this working?

**Comment by danielshahaf** [comment] 2017-06-02 18:20
> If I enable menu select using
> `zstyle ':completion:*:*:*:*:*' menu select`,
> the functionality breaks. Is this expected?
> Is there a setting or workaround to get this working?

Which version of zsh are you using?  5.3.1 doesn't have the fix; only latest master does.

(I can't easily test that `zstyle` right now, but FWIW, my usual setting — which I assume I was testing with — is `zstyle ':completion:*' menu select=long-list select=3`.)

**Comment by ratheesh** [comment] 2017-06-03 03:51
@danielshahaf 
       I am using 5.3.1. But I also tried the latest master(a6135f6) branch. I still see this issue.
I tried zstyle config that you mentioned, I did not see any difference.

**Comment by danielshahaf** [comment] 2017-06-03 03:54
Reopening per @ratheesh's last comment.  @all Can somebody investigate this?

**Comment by danielshahaf** [comment] 2017-06-03 03:55
(Sorry for shouting. I typed "all" in lowercase; I think it's a github bug.)

**Comment by m0vie** [comment] 2017-06-03 15:39
In https://github.com/zsh-users/zsh-syntax-highlighting/commit/462779629a0c66e652d3bf9f8a1f18330f379ee7

the minimum version to allow highlighting was increased to 5.3.2, which is not yet released.

So there is currently no version that supports it.

The FAQ is still outdated, see #423

**Comment by ratheesh** [comment] 2017-08-08 06:33
@m0vie @danielshahaf 
I still observe this issue with zsh v.5.4 that was tagged yesterday  and latest zsh-syntax-highlighting module.
I am not sure if I am missing something during testing.

**Comment by danielshahaf** [comment] 2017-08-09 18:59
With zsh 5.3.1-test-2-0-gd17f9d32f (similar to 5.4) and `autoload compinit; compinit; zstyle :completion:\* menu select` and `cd /etc/<TAB><TAB><TAB>`, the various /etc/foo names being completed are not underlined.  However, the trailing slash on dirs _is_ bold.

The fix mentioned about is about zle-line-pre-redraw which is not used by the master branch; it _is_ used by the feature/redrawhook branch, however, the behaviour there is similar to the behaviour on master.

Could somebody please confirm (a) that the above is a valid test case for this issue, (b) that it used to work at one time with some (which?) combination of zsh and z-sy-h?

**Comment by m0vie** [comment] 2017-08-12 16:45
This feature only works correctly, if the zle-line-pre-redraw hook is used. It does *not* work correctly with latest zsh master / z-sy-h master.

About your questions:
(a) Yes, that seems to be a valid test case. The bold trailing slash you are seeing is due to zsh iteself (`zle_highlight[suffix]`).
(b) With zle-line-pre-redraw, this has been working since zsh 5.3.

By the way: I just saw that my comment from June 03 was totally misplaced, that one was about the isearch issue. (I removed it)

**Comment by ratheesh** [comment] 2017-08-13 09:29
with `zsh 5.4.1` and `z-sy-h` on `feature/redrawhook` branch, this feature works fine for me.
I _could not_ test it on zsh 5.3

**Comment by ratheesh** [comment] 2017-08-13 11:50
Just to add, `z-sy-h` `feature/redrawhook` branch breaks zsh-autosuggestions plugin highlighting.

**Comment by ratheesh** [comment] 2017-09-12 12:22
may I know if any got a chance look into this.

**Comment by danielshahaf** [comment] 2017-09-14 05:26
Sorry, missed your comments.

> with zsh 5.4.1 master and z-sy-h feature/redrawhook branch, this feature works fine for me.

Okay; labeled as such and added to the list in #245.  Hopefully redrawhook will be merged for 0.7.0 so this will be fixed then.

> Just to add, z-sy-h feature/redrawhook branch breaks zsh-autosuggestions plugin highlighting.

Please test with latest master of both and if it's still a problem, open a new issue.  Thanks!

**Comment by JacksonGariety** [comment] 2020-04-11 22:09
I'm experiencing this, which has been an issue for nine years, wow (#25)! What's the latest fix?

**Comment by danielshahaf** [comment] 2020-04-11 23:53
Will be fixed when redrawhook is fixed, hopefully soon.  In the meantime you can workaround this by using (or merging) the `feature/redrawhook` branch.

**Comment by nhooyr** [comment] 2020-05-26 16:58
@danielshahaf Why isn't that branch just merged into master?

I'm seeing this in latest zsh 5.8 from homebrew.

**Comment by danielshahaf** [comment] 2020-05-26 17:45
Because it causes a regression in a certain class of use-cases (see #418 and #579) and we're trying to figure out how to solve that regression without making a change to zsh itself (https://github.com/zsh-users/zsh/pull/57), waiting for the next zsh release, and requiring all users to upgrade to that.

**Comment by nhooyr** [comment] 2020-05-26 23:49
Awesome, thanks for responding!

**Closed** 2020-08-09 11:11 UTC
Labels: Improvement, Upstream, widget-wrapping

**Comment by nhooyr** [comment] 2020-08-09 15:24
🎉🎉

Congrats guys!

**Comment by danielshahaf** [comment] 2020-08-10 02:29
Thanks :-)
