### ISSUE TITLE
alias highlighting is broken in specific situations

### ISSUE THREAD

**Issue by lockejan** [zsh-users/zsh-syntax-highlighting#847] opened 2021-12-17 12:27 UTC
Hi,
I just ran into an issue with alias highlighting.
In particular this specific alias `lsp-update` breaks the highlighting:

```
alias update="echo foo && lsp-update"
alias lsp-update='cd ~/.cache/nvim/nlua/sumneko_lua &&
git pull &&
cd 3rd/luamake &&
compile/install.sh &&
cd ../.. &&
./3rd/luamake/luamake rebuild && cd '
``` 

I tested this also against the `fast-syntax-highlighting` plugin.
The issue is only present in `zsh-syntax-highlighting`.

**Comment by danielshahaf** [comment] 2021-12-17 13:56
By "breaks" I assume you mean "is highlighted in red".

That'll be because compile/install.sh does not exist at the current directory at the time highlighting runs. It's not a bug, it's a feature.

Recommend to convert the alias to a function. That'll also fix the cpp(1)-like macro expansion precedence bug the alias has when used in SHORT_LOOPS contexts.

Next time please minimize your reproduction recipes and include version numbers.

**Comment by danielshahaf** [comment] 2021-12-17 15:09
Closing as @lockejan has ack'd.

**Closed by danielshahaf** 2021-12-17 15:09 UTC
Labels: Question

**Comment by lockejan** [comment] 2021-12-17 15:14
>By "breaks" I assume you mean "is highlighted in red".

Yes, I do.

>Recommend to convert the alias to a function. That'll also fix the cpp(1)-like macro expansion precedence bug the alias has when used in SHORT_LOOPS contexts.

Thanks for the explanation, I appreciate your suggestion to put it into a function. Fixes it.

> Next time please minimize your reproduction recipes and include version numbers.

Sorry for missing out on the meta details. How minimal would have been enough? IMO it's fairly minimal already.🤔

**Comment by danielshahaf** [comment] 2021-12-17 21:58
> Sorry for missing out on the meta details. How minimal would have been enough? IMO it's fairly minimal already. 🤔  
Something along the lines of:

```zsh
alias lorem='cd foo && ./bar'
mkdir foo
touch foo/bar
chmod +x foo/bar
```

Plus confirming it's run in `zsh -f` and what the command line being highlighted is (`lorem`).

tests/generate.sh basically does this, but you weren't expected to know that tool.

Cheers!
