### ISSUE TITLE
Play well with zsh-autosuggestions or regression in 7edd081

### ISSUE THREAD

**Issue by balta2ar** [zsh-users/zsh-syntax-highlighting#164] opened 2015-03-11 11:14 UTC
Described the issue in [comments](https://github.com/zsh-users/zsh-syntax-highlighting/commit/7edd08156e98b8be451bd5a034714746894b2a3d) to the commit, citing here:

This commit broke highlighting for me: http://i.imgur.com/AajFXtS.png
I typed `conda` and then 1) pressed `C-e` on the first line 2) `Alt-f` several times on the second line 3) typed the whole string manually on the third line.

In fact, If I put source highlighting in the end of my zshrc, I get the following errors when I press `Alt-f` and `Alt-b`:
```
No such widget `.autosuggest-forward-word-orig'
No such widget `.autosuggest-backward-word-orig'
```

However if I put zsh-autosuggestions in the end, it works. Well, it worked before this commit:
``` bash
fpath=(~/rc.arch/bz/thirdparty/zsh-completions/src $fpath)
source ~/rc.arch/bz/thirdparty/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/rc.arch/bz/thirdparty/zsh-autosuggestions/autosuggestions.zsh
# Enable autosuggestions automatically
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init
```

**Comment by randomize** [comment] 2015-03-26 11:12
Sorry to hear that this change caused a regression in relation with other zsh plugin. I've described the exact changes and reasoning behind them while struggling with old #77 issue this commit was addressing to.

Main _zsh-syntax-highlighting_ module's task is forming a **global** ```region_highlight``` value by combining the results of multiple sub-modules (highlighters). Highlighters are called sequentially in ```_zsh_highlight()```. From highlighter's perspective it has exclusive access to ```region_highlight``` seeing it like a **local variable** isolated from other highlighters. 

Main module is very tricky because it has to present "personal version" of ```region_highlight``` to each highlighter, cache results for performance, isolate changes, but combine them in final version of ```region_highlight``` on ```_zsh_highlight()``` exit . That's why highlighters should strictly obey the rules and modify ```region_highlight``` **only** in a special callback function ```"_zsh_highlight_${highlighter}_highlighter"```. 

If you look at the source of _zsh-autosuggestions_, you'll notice that not only it modifies ```region_highlight``` outside of the callback, but actually calls ```_zsh_highlight()``` manually when it want's to.
https://github.com/tarruda/zsh-autosuggestions/blob/master/autosuggestions.zsh#L122
I guess that regression is caused by some assumptions about _zsh-syntax-highlighting_ internals that authors of _zsh-autosuggestions's_ made and hacky integration no longer works with this change.

As for change itself, you can see from comments and original discussion, it cleaned main module's algorithm by removing dangerous diff-string magic that failed badly when ```SH_WORD_SPLIT``` is set, resulting #77. I wasn't sure about syntactic details (zsh language is hard to master) but it works good and was checked by _zsh-syntax-highlighting_ maintainer. 

Possibly related old issue btw
https://github.com/tarruda/zsh-autosuggestions/issues/6

**Comment by balta2ar** [comment] 2015-03-26 11:43
@randomize Thank you for the detailed explanation! I've whined a little in the issue you referenced, let's hope the author will have time to address the problem. Until then, it looks like I gotta use detached HEAD of zsh-syntax-highlighting.

**Comment by danielshahaf** [comment] 2015-09-06 21:07
Sounds like this has been fixed by https://github.com/tarruda/zsh-autosuggestions/issues/55, so closing. Feel free to reopen if there's a further issue.

**Closed by danielshahaf** 2015-09-06 21:07 UTC
