### ISSUE TITLE
strange behavior when using 'setopt ignoreeof' and zsh-syntax-highlighting

### ISSUE THREAD

**Issue by 400thecat** [zsh-users/zsh-syntax-highlighting#377] opened 2016-10-02 11:22 UTC
I have `setopt ignoreeof` at the beginning of my `.zshrc` file. Normally, when I pres `ctrl+d` I get following message: `zsh: use 'exit' to exit.` That is desired behavior.

Now when I source `sh-syntax-highlighting` in `.zshrc`, suddenly `ctrl+d`  behaves weird. When I pres `ctrl+d` I get a list of all available commands, and at the bottom of the screen `At Top: Hit TAB for more, or character to insert`.

**Comment by danielshahaf** [comment] 2016-10-02 12:50
This is another variant of issue #245.  The fix to this issue is to be merged soon, however, it requires zsh 5.3.  Until then, you can try the following workaround:

```zsh
ctrl-d() { zle -M "zsh: use 'exit' to exit."; return 1 } 
zle -N ctrl-d
```
Put that in your .zshrc before sourcing z-sy-h.  (I tried just `bindkey -r "^D"`, but that removed the `use 'exit' to exit` message as well.)

For future reference, the message you got is because <kbd>Ctrl+d</kbd> also serves as a "list completions" binding; it is bound to the `delete-char-or-list` widget, not to `delete-char`.

**Comment by danielshahaf** [comment] 2016-10-02 12:53
Sorry, that example was incomplete.  It needs another line:

```zsh
ctrl-d() { zle -M "zsh: use 'exit' to exit."; return 1 } 
zle -N ctrl-d
bindkey '^D' ctrl-d
```

**Comment by danielshahaf** [comment] 2020-07-14 20:45
Fixed on the feature/redrawhook branch.

**Closed** 2020-08-09 11:11 UTC
Labels: Bug, Upstream, widget-wrapping

**Comment by phy1729** [comment] 2024-01-06 18:45
I can't reproduce this. Starting from zsh -f
```
setopt ignoreeof
. <path to z-sy-h>
<ctrl-d>
```
I get the `zsh: use 'exit' to exit.` message. zsh 5.9 and z-sy-h 0.8.0.
