### ISSUE TITLE
Aliases of precommand with flag that takes an argument

### ISSUE THREAD

**Issue by phy1729** [zsh-users/zsh-syntax-highlighting#540] opened 2018-10-01 15:59 UTC
```
alias sdu='sudo -u'
sdu phy1729 echo foo
```

Should highlight phy1729 as normal (as it's an argument) and echo as a command. The parser currently treats phy1729 as the command.

**Comment by danielshahaf** [comment] 2018-10-03 08:12
I'm surprised `phy1729` is taken to be a command word.

**Comment by phy1729** [comment] 2018-10-03 13:08
The issue is that even once precommands is merged only the first word of an alias is run through the state machine.

**Comment by danielshahaf** [comment] 2018-10-15 09:10
Duplicate of newer #552.

**Closed** 2018-10-15 09:11 UTC
Labels: Bug, syntax:command-word
