### ISSUE TITLE
Unable to highlight aliases with variables

### ISSUE THREAD

**Issue by joeky888** [zsh-users/zsh-syntax-highlighting#627] opened 2019-07-29 01:38 UTC
After upgrading to recent version of zsh-syntax-highlighting,

alias highlighting is not showing anymore.

Step to reproduce:

```sh
$ export LS_ARGS='-a -l -h' && alias lslh='ls $(echo $LS_ARGS)'
$ lslh # No highlighting
```

**Comment by phy1729** [comment] 2019-07-29 02:51
It looks like https://github.com/zsh-users/zsh-syntax-highlighting/blob/b55832c5f849b2416c83ce3a665cf4bef2dc4d48/highlighters/main/main-highlighter.zsh#L1077 is passing down `ec` as BUFFER (`$arg[i,end_pos]`) not `echo $LS_ARGS`. Haven't figured out why yet, but it must be some interaction with alias and end_pos. 9cc0060 didn't cause that bug, but did expose it.

In the mean time you can work around with using `ls $=LS_ARGS` instead of using `$(echo` to do the word splitting (or I suppose a tied array `typeset -Tx LS_ARGS ls_args ' '; ls_args=(-a -l -h)`).

Please do not close the issue as this is still a bug in z-sy-h that should be fixed.

**Comment by phy1729** [comment] 2019-07-30 01:34
I think the fix is fairly simple
```diff
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index b0c5c92..a1bf4aa 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -1059,7 +1059,7 @@ _zsh_highlight_main_highlighter_highlight_argument()
        elif [[ $arg[i+1] == $'\x28' ]]; then
           start=$i
           (( i += 2 ))
-          _zsh_highlight_main_highlighter_highlight_list $(( start_pos + i - 1 )) S $has_end $arg[i,end_pos]
+          _zsh_highlight_main_highlighter_highlight_list $(( start_pos + i - 1 )) S $has_end $arg[i,-1]
           ret=$?
           (( i += REPLY ))
           highlights+=(
```
We want to pass down the rest of `$arg` (as _highlight_list will figure out where the closing brace is), so use -1 rather than end_pos. end_pos is for highlighting purposes and is not updated inside alias expanded words. Passes tests, but I'm tired, so I should be double checked (if by no one else than future me).

**Comment by joeky888** [comment] 2019-07-30 02:12
Works for me.

**Comment by danielshahaf** [comment] 2019-07-30 13:30
@phy1729 I haven't done a full review (ENOTIME) but briefly:

- The patch isn't against current master.  (Line numbers don't match)
- There are multiple instances of `$arg[i,end_pos]`; don't forget to review them too
- Docstring of `_zsh_highlight_main_highlighter_highlight_list` agrees with your change
- Is the condition of the `for (( ; i <= end_pos - start_pos ; i += 1 )); do` loop correct?
- Will this cause quadratic behaviour on command lines such as `: $(a_1) $(a_2) … $(a_n)`? That is, will `$(a_i)` be highlighted `n-i+1` times?

**Comment by danielshahaf** [comment] 2019-12-27 09:28
In current master, with the example in the OP, `lslh` is highlighted in green.

@phy1729 Can we close this issue?  Or is there something left to do here?

**Comment by danielshahaf** [comment] 2019-12-27 09:29
Bumping the milestone.  0.7.0 is overdue to be released; large/destabilizing/unfinished changes will have to wait for 0.8.0.

**Comment by danielshahaf** [comment] 2020-01-12 20:40
139ea2b189819c43cc251825981c116959b15cc3 was committed to master which includes the change in the above diff.  It also addresses my review points there.  Calling this done.

**Closed by danielshahaf** 2020-01-12 20:40 UTC

**Comment by latipun7** [comment] 2020-06-05 10:04
@danielshahaf , I recently has similar issue. My syntax-highlighting version is 00c0c765509538de207173fc787d364eedd48d6b .

I make alias
```zsh
alias psudo='sudo env "PATH=$PATH"'
```

but psudo is highlighted as red. I successfully run that alias without error. 

![psudo](https://i.imgur.com/6WfndfA.png)

Thanks.

**Comment by danielshahaf** [comment] 2020-06-05 12:14
Please file a new issue.

Try `alias psudo='sudo env PATH="$PATH"` as a workaround.

**Comment by latipun7** [comment] 2020-06-05 21:30
@danielshahaf 
Seems I can't reproduce that with another environment variables below:

```zsh
alias test1='echo $HOME'
alias test2='echo "$HOME"'
alias test3='echo ${HOME}'
alias test4='echo "${HOME}"'
alias test5='echo TEST=$HOME'
alias test6='echo "TEST=$HOME"'
```

even with `test6` that roughly has same form as `alias psudo='sudo env "PATH=$PATH"'`.

Yeah, as workaround I set my psudo alias as `alias psudo='sudo env PATH="$PATH"'` for now, and it worked.

I can't write another issue with good description for that specific bug for now.
Sorry.

**Comment by phy1729** [comment] 2020-06-05 22:10
`sudo env "PATH=$PATH"`
First word is `sudo` which is a known precommand, so next word will be parsed as a command.
Next word is `env` which is a known precommand, so next word will be parsed as a command.
Next word is `"PATH=$PATH"`. There's a bug in z-sy-h that when parsing a command (`$this_word == *:start:*`) an assignment is recognized even if it's no long the true start of a command (i.e. after a precommand), so `command foo=bar echo baz` parses `foo=bar` as an assignment and `echo` as the command even though command will error as `foo=bar` isn't a command. However in the case of `env` this mostly is desired. `env` being a command allows for quoted arguments just like any other, but assignments at the beginning of a command must not be quoted.

**Comment by danielshahaf** [comment] 2020-06-06 00:19
Created #743 for this.  Please continue discussion there.

@phy1729 Thanks for the write up.  That's what I figured too; I was going to write that up when I arrived at a full-sized keyboard, but you beat me to it.  Thanks again.
