### ISSUE TITLE
Aliases that start with an assignment are highlighted as error

### ISSUE THREAD

**Issue by tonylambiris** [zsh-users/zsh-syntax-highlighting#554] opened 2018-10-17 17:16 UTC
![gnome-shell-screenshot-i1jwqz](https://user-images.githubusercontent.com/14058972/47104149-c584f400-d20e-11e8-832f-f1b2670c162b.png)

**Comment by danielshahaf** [comment] 2018-10-17 17:32
That probably means `optirun` doesn't exist as a function, hashed command, or external command.

**Comment by tonylambiris** [comment] 2018-10-17 18:05
@danielshahaf it does:
![gnome-shell-screenshot-5789qz](https://user-images.githubusercontent.com/14058972/47106871-b81f3800-d215-11e8-8eb6-ac88f0db2d41.png)

**Comment by danielshahaf** [comment] 2018-10-17 18:10
I can reproduce this, thanks. `alias ls='x=y ls'; ls` is all it takes (there was no need for screenshots, really).

**Comment by danielshahaf** [comment] 2018-10-17 18:16
It doesn't even have to be cyclic.  Any alias that starts with an assignment triggers this: `alias x='a=1 foo'; x`.  It enters this block with `$arg` being the assignment:

https://github.com/zsh-users/zsh-syntax-highlighting/blob/47c2b7e1851375c3a9d3c1faec5851fc8409da08/highlighters/main/main-highlighter.zsh#L546-L547

So... how do we recognize a valid assignment?  Assignments can have subscripts (`l[1]=value`), and those can have subscript flags (`l=(foo bar); l[(r)foo]=baz`).

**Comment by sileht** [comment] 2018-10-20 19:38
I have "git bisect" this and the faulty commit is 57386f30aec8612fd1854bdd60b64a7e70acf57b

**Comment by phy1729** [comment] 2018-10-20 19:40
This issue should be fixed once #556 is in.

**Comment by sileht** [comment] 2018-10-20 19:42
Thanks, I just tested it and it works for me

**Comment by phy1729** [comment] 2018-10-21 02:37
Fixed in cb8c736 #556.

**Closed by phy1729** 2018-10-21 02:37 UTC
Labels: Bug, syntax:command-word
