### ISSUE TITLE
More elegant way to use as user

### ISSUE THREAD

**Issue by tuyenpm9** [zsh-users/zsh-syntax-highlighting#589] opened 2018-12-03 04:18 UTC
Currently zsh-syntax-highlighting.zsh must strictly be sourced manually, e.g: if you put the necessary folders and files under same folder (zsh-syntax-highlighting) then source all *.zsh file under that folder arbitrarily, it gives many error due to zsh-syntax-highlighting.zsh source files in order somehow.

**Comment by danielshahaf** [comment] 2018-12-04 07:10
That's not a bug. That's just how programming works in virtually all imperative languages.

**Comment by danielshahaf** [comment] 2018-12-04 07:11
Closing, unless there are reasons why what you describe should work.?

**Closed by danielshahaf** 2018-12-04 07:11 UTC
