### ISSUE TITLE
Negative numbers are treated as 'single-hyphen-option'

### ISSUE THREAD

**Issue by crowsonkb** [zsh-users/zsh-syntax-highlighting#633] opened 2019-09-17 19:52 UTC
Negative numeric (integer or float) arguments should probably be left alone instead of treated as single hyphen options. In the meantime I am doing:

```zsh
ZSH_HIGHLIGHT_PATTERNS+=('-[[:digit:].][^[:IFS:]]#' 'fg=black')
```

This deals with patterns like: `-1`, `-1.2e3`, `-.3`, etc.

**Comment by danielshahaf** [comment] 2019-09-18 04:27
Give a complete example?

**Comment by danielshahaf** [comment] 2019-09-18 04:30
Are you talking about command lines or does this happen in `(( … ))` or  $`(( … ))`?

**Comment by danielshahaf** [comment] 2020-01-10 16:54
If it's in `$(( … ))`, then it's a duplicate of #607.  If it's in the command line, then it's generally intentional: comm(1) and svnserve(8), for example, use single-hyphen options that look like negative numbers.

**Closed by danielshahaf** 2020-01-10 16:54 UTC
