### ISSUE TITLE
conflict with zsh-autosuggestions

### ISSUE THREAD

**Issue by leon728** [zsh-users/zsh-syntax-highlighting#756] opened 2020-08-09 16:59 UTC
when loading both (zsh-autosuggestions and zsh-syntax-highlighting), text color of zsh-autosuggestions is not darkgray.
when loading only zsh-syntax-highlighting, evething works fine.
(reference: https://github.com/zsh-users/zsh-autosuggestions/issues/516)

it was caused by latest commit, using 2d60a47 works fine.

**Comment by danielshahaf** [comment] 2020-08-10 02:28
How could https://github.com/zsh-users/zsh-autosuggestions/issues/516 be related to this? It's from March and the latest commit is from yesterday. Furthermore, that issue doesn't mention what branch or tag of zsh-syntax-highlighting was used. I assume you just mean your symptoms are the same as the screenshots in that issue.

The latest commit is the redrawhook merge. This issue was reported before the merge and believed fixed then: see issues #579 and #735. I'll look into this again.

Please report the version numbers of zsh and zsh-autosuggestions.

**Comment by leon728** [comment] 2020-08-10 05:30
Yes, I mean symptoms are the same as https://github.com/zsh-users/zsh-autosuggestions/issues/516

ZSH version:
zsh 5.8 (x86_64-ubuntu-linux-gnu)

zsh-autosuggestions version:
https://github.com/zsh-users/zsh-autosuggestions/commit/ae315ded4dba10685dbbafbfa2ff3c1aefeb490d

zsh-syntax-highlighting version:
https://github.com/zsh-users/zsh-syntax-highlighting/commit/2d60a47cc407117815a1d7b331ef226aa400a344 : ok
https://github.com/zsh-users/zsh-syntax-highlighting/commit/c14fcad3b08e19dce750b4b0eb6cc597e0f93d57 : failed

you fixed https://github.com/zsh-users/zsh-syntax-highlighting/issues/579 in https://github.com/zsh-users/zsh-syntax-highlighting/commit/cb33cc0081234c0f8e48d89e0ba81cf58a8f7635
but in my test, https://github.com/zsh-users/zsh-syntax-highlighting/commit/9ce3540d74c12b24a3f705a115f1f7b8f997ced6 is ok, https://github.com/zsh-users/zsh-syntax-highlighting/commit/cb33cc0081234c0f8e48d89e0ba81cf58a8f7635 failed

reproduce (https://github.com/zsh-users/zsh-syntax-highlighting/issues/579):
`exec zsh -f`
`source path/to/zsh-autosuggestions/zsh-autosuggestions.zsh`
`source path/to/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`
`echo one two three`
`echo  # notice that 'one two three' are faint from autosuggestions.`

**Comment by danielshahaf** [comment] 2020-08-10 05:39
Thanks for the information!  That's very helpful.  The bisection to 9ce3540d74c12b24a3f705a115f1f7b8f997ced6 should make this easy to track down.

**Comment by danielshahaf** [comment] 2020-08-10 07:28
Reproduced.  I also tried to vary each of the three relevant versions, with the following results:

zsh version | z-asug version | z-sy-h version | behaviour
----------- | -------------- | -------------- | ---------
5.8 | ae315ded4dba (== v0.6.4 == current master) | c14fcad3b08e (current master) | :-1: shows "one two three" in white
5.8 | ae315ded4dba (== v0.6.4 == current master) | c14fcad3b08e (current master) + run `git revert cb33cc008123` | :+1: shows "one two three" in grey.
5.8 | eff0894a138f (current `develop`) | c14fcad3b08e (current master) | :+1::-1: When I type the first `e` of the second `echo`, that `e` is shown in bold red (z-sy-h's `unknown-token`) and the remainder of the line is correctly shown in bold black (as a suggestion); however, as soon as I type the following `c`, the bug resurfaces.
master | ae315ded4dba (== v0.6.4 == current master) | c14fcad3b08e (current master) | :+1: The remainder of the line is in grey, regardless of how much of the `echo` has been typed in.

**Comment by danielshahaf** [comment] 2020-08-10 07:40
So, the problem is that `is-at-least 5.8.0.2` returns true on zsh 5.8.

A workaround is to use `is-at-least 5.8.0.2 $ZSH_VERSION.0`.  That does the right thing under { z-asug master, z-asug develop } × { zsh 5.8, zsh master }.

Pushed in 3944a44ffe44 and closing as fixed.  Reopen if it's not.

**Closed** 2020-08-10 07:40 UTC

**Comment by danielshahaf** [comment] 2020-08-10 08:13
Reported the bug upstream in https://zsh.org/workers/47314.  Thanks again for the report, particularly for bisecting it to that specific commit!
