### ISSUE TITLE
Aliases that resolve to command substitutions (backticks) are highlighted as errors

### ISSUE THREAD

**Issue by lukepass** [zsh-users/zsh-syntax-highlighting#617] opened 2019-06-19 10:56 UTC
Hello, I recently upgraded to the latest version of zsh-syntax-highlighting but the aliases are not highlighted correctly:

`plugins=(git symfony2 history-substring-search wd zsh-syntax-highlighting)`

How can I fix it? Thanks!

![image](https://user-images.githubusercontent.com/6429961/59760005-950bc300-9291-11e9-8552-6fb72a76f9a8.png)

**Comment by danielshahaf** [comment] 2019-06-19 16:00
The latest version highlights aliases according to what they resolve to.  I assume that ``% `_symfony_console` foo bar`` is also highlighted in red?  (I can't test that right now)

@phy1729 might know more (but I don't know when he might have time to look). 

By the way, are you sure the alias is defined correctly?  Should it have been defined with double quotes?

**Comment by lukepass** [comment] 2019-06-20 07:16
Hello @danielshahaf!
Yes, the alias is also resolved in red but it does indeed work. This alias is automatically created by the Symfony native plugin for Oh My Zsh:

![image](https://user-images.githubusercontent.com/6429961/59828721-e5d7f600-933b-11e9-8cf8-9cb9593fa8ca.png)

In case you don't use Symfony, the `php bin/console` is used to launch command to update the database, create controllers etc...

Thanks.

**Comment by danielshahaf** [comment] 2019-06-20 11:48
I still would like to understand the design choices around the alias. What's a valid use-case for defining an alias with command substitutions (backticks) on the right-hand side?  (I'm not familiar with symfony.)  It's not idiomatic, and there are more robust, equivalent alternatives.

Regarding zsh-syntax-highlighting, perhaps we could highlight such aliases differently: false positive `unknown-token` (red) highlightings should be avoided.

We have begun preparations for the 0.7.0 release. Is there any reason for this to be a blocker? I assume that "command substitutions in command position are highlighted in red" isn't a regression.

**Comment by lukepass** [comment] 2019-06-20 12:25
Unfortunately I don't know the design choices behind this choice, the alias definition of the plugin is very simple:

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/symfony2/symfony2.plugin.zsh

```
# Symfony2 basic command completion

_symfony_console () {
  echo "php $(find . -maxdepth 2 -mindepth 1 -name 'console' -type f | head -n 1)"
}

_symfony2_get_command_list () {
   `_symfony_console` --no-ansi | sed "1,/Available commands/d" | awk '/^  ?[^ ]+ / { print $1 }'
}

_symfony2 () {
   compadd `_symfony2_get_command_list`
}

compdef _symfony2 '`_symfony_console`'
compdef _symfony2 'app/console'
compdef _symfony2 'bin/console'
compdef _symfony2 sf

#Alias
alias sf='`_symfony_console`'
alias sfcl='sf cache:clear'
alias sfsr='sf server:run -vvv'
alias sfcw='sf cache:warmup'
alias sfroute='sf debug:router'
alias sfcontainer='sf debug:container'
alias sfgb='sf generate:bundle'
alias sfgc='sf generate:controller'
alias sfgcom='sf generate:command'
alias sfge='sf doctrine:generate:entity'
alias sfsu='sf doctrine:schema:update'
alias sfdc='sf doctrine:database:create'
alias sfdev='sf --env=dev'
alias sfprod='sf --env=prod'
```

Unfortunately I don't know which version I was using before this, but the `sf` command was highlighted in green.

Please let me know if I can help somehow!

Thanks!

**Comment by phy1729** [comment] 2019-06-25 03:29
The change was likely caused by https://github.com/zsh-users/zsh-syntax-highlighting/commit/cb8c736a564e0023a0ef4e7635c0eb4be5eb56a4 . PR #568 wouldn't change things since the command substitution in `` `echo echo` foo`` is highlighted as `unknown-token` and `unknown-token` is propagated up to style the alias itself.

This is another case where we need to distinguish between an error and refusal to evaluate due to possible side effects.

I would encourage you to change the definition of `_symfony_console` to something like
```zsh
_symfony_console() {
    local consoles=(console(N.) */console(N.))
    php $console[1] "$@"
}
```

Which can be invoked directly instead of creating a seemingly useless subshell.

**Comment by lukepass** [comment] 2019-06-25 14:08
Hello, unfortunately the Symfony plugin is not developed by me, can I add the suggested script in my .zshrc?

**Comment by shortspecialbus** [comment] 2019-11-07 20:38
I have a similar issue with an alias for colored diff output.  Alias is:

alias cdiff='wdiff -w "$(tput bold;tput setaf 1)" -x "$(tput sgr0)" -y "$(tput bold;tput setaf 2)" -z "$(tput sgr0)"'

I'm not sure how to do this cleanly without being how it is, exactly, but perhaps it could also be written better.  Either way, zsh-syntax-highlighting started highlighting it red at some point semi-recently, likely the same cause as the original.

**Comment by danielshahaf** [comment] 2019-11-07 21:12
It doesn't seem like the issue @phy1729 described [above](https://github.com/zsh-users/zsh-syntax-highlighting/issues/617#issuecomment-505267091), but as a workaround, you can change the alias to a function:

```zsh
cdiff () { wdiff -w "$(tput bold;tput setaf 1)" -x "$(tput sgr0)" -y "$(tput bold;tput setaf 2)" -z "$(tput sgr0)" "$@" }
```

(Aside: Thanks for sharing that; I'll add this to my zshrc.  I usually use `icdiff` and `git diff --word-diff=color`.)

**Comment by phy1729** [comment] 2019-11-08 02:01
The commit I just pushed fixes the issue locally. Please confirm it fixes it for you as well.

The issue was that `end_pos` was incorrectly used as a shortcut for the end of `arg`. In an alias, that isn't true because `start_pos` and `end_pos` are not updated while parsing arguments expanded from an alias.

**Comment by shortspecialbus** [comment] 2019-11-08 13:09
Hello, that was a super quick turnaround!  Thanks!

1. Sorry about it actually being different - I took a quick glance at the issue and saw a similarity with $(blah) in the definition for the _symfony_console and sort of stopped there and reported it - I was in the middle of something work related and only had time to see if it was on my end, saw this, and did some whining.

2. The update appears to work!  I quick tested most of my aliases and functions and the only ones that didn't turn green were some that the target commands weren't relevant on the box I was on, so it's not just blindly turning them green either :)

3. Thank you again!  And yeah, it's a situationally useful little diff tool.

**Comment by danielshahaf** [comment] 2019-11-08 13:30
Thanks for following up and confirming the fix!  For future reference, I'd have preferred it if you'd opened a new issue and said you thought it was a duplicate of #617 but wasn't sure.  Numbers are cheap, and it's easier to handle duplicate issues than to handle a single issue number that discusses several distinct defects.  Cheers!

**Comment by shortspecialbus** [comment] 2019-11-08 13:36
Noted - apologies.  You'd think I'd know that, being a sysadmin and getting grumpy when someone stacks a ticket, but for whatever reason the developers I work with most often get cranky if you open too many tickets and so I've developed some bad habits out of that :\  Take care!

**Comment by kbd** [comment] 2020-03-06 19:30
Looks like this is what's biting me here?

![Screen Shot 2020-03-06 at 12 27 52 PM](https://user-images.githubusercontent.com/728060/76115759-00bfc880-5fa6-11ea-9add-8f1a1ff6904c.png)

**Comment by danielshahaf** [comment] 2020-03-06 19:54
@kbd Your example works fine in current master.  If it doesn't, please open a new issue.  Thanks.

**Comment by shortspecialbus** [comment] 2020-03-06 19:56
@kbd I can confirm that it's working properly for me as well.

**Comment by kbd** [comment] 2020-03-06 19:56
> Your example works fine in current master.

Great, thanks!

**Comment by danielshahaf** [comment] 2020-03-06 21:35
> Edit: fwiw I'm using the Homebrew-packaged 0.7.1.

There are no relevant changes between 0.7.1 and master.  If after defining `alias e='$EDITOR'`, uses of the alias are highlighted in red but execute successfully, please open a new issue.

I've re-titled this issue to clarify its focus.  Hopefully that will prevent this issue from being overloaded with a fourth meaning…

**Comment by danielshahaf** [comment] 2020-03-16 21:58
Closing as duplicate of #695 (which was filed much later, but still).

**Closed by danielshahaf** 2020-03-16 21:58 UTC
Labels: Bug, Question, syntax:command-word
