### ISSUE TITLE
[Feature request] Add option to make the comments italic

### ISSUE THREAD

**Issue by danielfalbo** [zsh-users/zsh-syntax-highlighting#807] opened 2021-04-08 19:08 UTC
Italic is not widely supported in terminal emulators but for the ones who do it'd be a pretty cool feature, especially for people who use fonts like Victor Mono that are very lovely for italic text.

**Comment by phy1729** [comment] 2021-04-08 19:14
Duplicate of #432. The request would need to be made upstream to zsh.

**Closed by phy1729** 2021-04-08 19:14 UTC
