### ISSUE TITLE
zsh-syntax-highlighting.zsh:31: invalid alias '=' encountered while printing aliases

### ISSUE THREAD

**Issue by sunjintw** [zsh-users/zsh-syntax-highlighting#526] opened 2018-08-23 03:32 UTC
When I source the .zshrc, I see below issue:

![image](https://user-images.githubusercontent.com/15727276/44503274-16251880-a6c8-11e8-9daf-1afa03d4783b.png)

![image](https://user-images.githubusercontent.com/15727276/44503298-35bc4100-a6c8-11e8-9b4b-686671546037.png)

**Comment by danielshahaf** [comment] 2018-08-23 08:14
z-sy-h undefines/redefines aliases so they wouldn't be effective as it's parsed. Aliases that begin with `=` can't be defined by zsh's API. Thus, the warning you see.

Probably the same issue as #523 except that you use zsh>=5.3.1.

Whoever uses such aliases should get zsh upstream to provide a _forward compatible_ syntax for creating them (or at least help with the aforementioned conversion to `autoload`).

Excuse brevity.

**Comment by NightMachinary** [comment] 2019-07-07 05:05
@danielshahaf I use ‘=‘ as an alias, and it works just fine except this warning?

**Comment by danielshahaf** [comment] 2019-07-07 10:03
The warning is generated by zsh itself, not by z-sy-h:

```zsh
% Src/zsh -fc 'aliases[=]=; alias -L' 
zsh:1: invalid alias '=' encountered while printing aliases
```

With my z-sy-h hat, I'm closing this issue as it's not a bug in z-sy-h (notwithstanding that [using autoload](https://github.com/zsh-users/zsh-syntax-highlighting/issues/252) will work around this).

With my zsh upstream hat, I suggest that you ask whoever maintains your zshrc to ask zsh-users@ to consider allowing `=` to be the LHS of an alias.  It should be simple enough to support that, and unlike other aliases of the form `=foo`, it would not collide with the syntax of the (on-by-default) EQUALS option.

Ideally, whoever approaches zsh-users@ with this idea should be willing to implement it (in C) if it's accepted.

**Closed by danielshahaf** 2019-07-07 10:03 UTC
Labels: Forward compatibility, Question, Upstream, syntax:command-word
