### ISSUE TITLE
syntax-highlighting stops highlighting on autocompletion sometimes

### ISSUE THREAD

**Issue by DarthGandalf** [zsh-users/zsh-syntax-highlighting#102] opened 2013-01-04 17:01 UTC
Example: type `grep<space><tab>`
Before pressing `<tab>` the word "grep" is green, as it should be. But after pressing `<tab>` it becomes grey. After that I type one more letter (or press backspace), and it becomes green again.

Another example: `if<space>(true)<tab>`

Using Gentoo
app-shells/zsh-4.3.17

Related issue: sorin-ionescu/prezto#359

**Comment by xuhdev** [comment] 2015-01-04 08:15
This also always happens to me. zsh-syntax-highlighting already rebinds all completion widgets to call `_zsh_highlight` to refresh. I guess maybe something else then refreshed the line back?

**Comment by guidovansteen** [comment] 2015-02-28 06:59
For those still bothered by this issue, fizsh addresses it as follows: 

`function _fizsh-expand-or-complete-and-highlight() {
  zle expand-or-complete
  _zsh_highlight_brackets_highlighter
  _zsh_highlight_line_highlighter
  _zsh_highlight_main_highlighter
  _zsh_highlight_cursor_highlighter
  _zsh_highlight_pattern_highlighter
  _zsh_highlight_root_highlighter
}

zle -N _fizsh-expand-or-complete-and-highlight _fizsh-expand-or-complete-and-highlight

bindkey "^I" _fizsh-expand-or-complete-and-highlight`

**Comment by danielshahaf** [comment] 2015-09-06 19:33
Duplicate of #90.

**Closed by danielshahaf** 2015-09-06 19:33 UTC
Labels: Bug
