### ISSUE TITLE
command highlight reversed after update

### ISSUE THREAD

**Issue by tmccombs** [zsh-users/zsh-syntax-highlighting#557] opened 2018-10-18 18:43 UTC
I just updated zsh-syntax-highlighting, and now if a command is valid it is highlighted as red, and invalid commands are highlighted as green

**Comment by danielshahaf** [comment] 2018-10-18 19:32
Works for me. Please give a reproducer that starts from `zsh -f`.

**Comment by tmccombs** [comment] 2018-10-18 20:12
hmm, actually my original description is wrong. What' happening is it is marking aliases that start with an environment variable as unknown-token.

For example:

```zsh
$ alias ls=''A=a ls"
$ ls
```
ls is highlighted as red. 

(this happens with `zsh -f`)

**Comment by danielshahaf** [comment] 2018-10-18 20:21
Duplicate of #554

**Closed by danielshahaf** 2018-10-18 20:21 UTC
Labels: Question

**Comment by tmccombs** [comment] 2018-10-18 20:33
ah, yes it is. thanks
