### ISSUE TITLE
"_zsh_highlight_call_widget: maximum nested function level reached; increase FUNCNEST?" error when plugin is used along with zsh-autocomplete

### ISSUE THREAD

**Issue by robole** [zsh-users/zsh-syntax-highlighting#812] opened 2021-05-19 13:57 UTC
Hi

Thanks for your work. I like the plugin.

One issue I have is that it doesn't play nice with the plugin [zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete). I get the error below when I execute most (all?) commands it seems.

![Kazam_screenshot_00000](https://user-images.githubusercontent.com/3703647/118823660-b8ab6e00-b8eb-11eb-8a3a-cd18e1768320.png)

I commented out all other plugin/scripts in my `zshrc` and found that it was by removing `zsh-autocomplete` made the error go away. See excerpt below:

```bash
#...

# Plugins
source ~/zsh-plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# leave as last plugin
source ~/zsh-plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

I have the latest of both plugins. You can find my entire zshrc in [this gist](https://gist.github.com/robole/80adc0829cf0fec9928ae06ce6d0df13)

I am running zsh 5.8 on ubuntu 20.04.

**Comment by danielshahaf** [comment] 2021-05-19 16:10
@robole Still investigating.  In the meantime, you might sourcing the two plugins in the opposite order, and/or the following patch (the caveat about interoperability, in the comment above the hunk context, doesn't apply to marlonrichert/zsh-autocomplete as it stands today).

```diff
diff --git a/zsh-syntax-highlighting.zsh b/zsh-syntax-highlighting.zsh
index d20dc5b..bad5c70 100644
--- a/zsh-syntax-highlighting.zsh
+++ b/zsh-syntax-highlighting.zsh
@@ -414,7 +414,7 @@ _zsh_highlight_call_widget()
 #
 #    See _zsh_highlight for the magic version number.  (The use of 5.8.0.2
 #    rather than 5.8.0.3 as in the _zsh_highlight is deliberate.)
-if is-at-least 5.8.0.2 $ZSH_VERSION.0.0 && _zsh_highlight__function_callable_p add-zle-hook-widget
+if is-at-least 5.3 $ZSH_VERSION.0.0 && _zsh_highlight__function_callable_p add-zle-hook-widget
 then
   autoload -U add-zle-hook-widget
   _zsh_highlight__zle-line-finish() {
```

**Comment by danielshahaf** [comment] 2021-05-19 16:13
zsh-autocomplete overwrites the z-sy-h internal implementation detail function that the error message is about (meaning the error might not be z-sy-h's fault at all, despite the function's name):

https://github.com/marlonrichert/zsh-autocomplete/blob/405c29211047968516c9dbd9f41146976725462e/module/.autocomplete.async#L29-L34

@marlonrichert Do not define functions in the `_zsh_highlight_*` namespace except as specifically permitted in the z-sy-h documentation.

**Comment by marlonrichert** [comment] 2021-05-20 16:59
@danielshahaf I'm not defining a new function in the `_zsh_highlight_*` namespace. Rather, I'm patching your existing function, because it breaks `kill`/`yank` widget chaining, as described in various issues here. (I'd point you to the right one, but I think you know better than I which one that is. 🙂) Yes, you have a fix for it, but that won't work until Zsh 5.9 is released.

`zsh-autocomplete` itself has a functional workaround for this problem, but as soon as `zsh-syntax-highlighting` is introduced, everything breaks again. Hence, the patch.

---

@robole I cannot reproduce your issue, no matter in which order I source the plugins. This makes me think there might be something interfering in your global rcs. Have you tried restarting with `exec zsh -d`? This disables global rc files.

Do [any of these issues](https://github.com/marlonrichert/zsh-autocomplete/issues?q=%22maximum+nested+function+level+reached%22) look like your problem? If not, feel free to open a new one.

**Comment by marlonrichert** [comment] 2021-05-20 17:45
> Do not define functions in the _zsh_highlight_* namespace except as specifically permitted in the z-sy-h documentation.

@danielshahaf [I already replied to your statement.](https://github.com/zsh-users/zsh-syntax-highlighting/issues/812#issuecomment-845290810) Feel free to copy-paste it here, but I'm not going to do that.

**Comment by danielshahaf** [comment] 2021-05-20 17:55
@robole Thanks for the update.  Closing, but reopen if it recurs.

**Closed by danielshahaf** 2021-05-20 17:55 UTC

**Comment by marlonrichert** [comment] 2021-05-21 17:38
@danielshahaf Patches welcome. ❤️

**Comment by danielshahaf** [comment] 2021-05-21 17:49
@marlonrichert It's not the responsibility of the z-sy-h authors to fix third party code that uses z-sy-h incorrectly.

**Comment by marlonrichert** [comment] 2021-05-21 17:56
@danielshahaf Patches welcome. ❤️

**Comment by danielshahaf** [comment] 2021-05-21 18:57
Full credit for humour.

However, in general, when product foo uses product bar, errors in foo's usage of bar are to be fixed by foo's maintainers.  That's how it is.  You wrote the bug and you maintain the project it is in, so it is you who should fix the bug.

**Comment by jottr** [comment] 2023-10-30 18:42
I see the same issue, even after disabling `zsh-autosuggest` (and completely restarting my shell) .

``` zsh
$ zsh --version
zsh 5.9 (arm-apple-darwin21.3.0)
```

``` zsh
$ true
_zsh_highlight_widget_zle-line-finish: job table full or recursion limit exceeded
```

``` zsh
cat ~/.zplug.zsh
# --- snip 
zplug 'zsh-users/zsh-syntax-highlighting', defer:2
# snip ---
```

What can I do?

**Comment by phy1729** [comment] 2023-10-31 23:17
This issue is already closed. Please open a new issue with a minimal reproducer starting from `zsh -f` and sourcing zsh-syntax-highlighting.
