### ISSUE TITLE
Typing . after .. will cause an error message to appear 

### ISSUE THREAD

**Issue by dongsiji** [zsh-users/zsh-syntax-highlighting#562] opened 2018-10-21 12:13 UTC
After typing .. in the terminal, additional . behind will cause 
```zsh-syntax-highlighting: BUG: _zsh_highlight_main_highlighter_expand_path: called without argument```
to be appended to the terminal.

**Comment by dongsiji** [comment] 2018-10-21 12:14
![image](https://user-images.githubusercontent.com/35907419/47266787-d797c700-d56d-11e8-9263-7aa48d0f6658.png)

**Comment by danielshahaf** [comment] 2018-10-21 13:10
Duplicate of #549. Thanks for the reproduction recipe.

**Closed** 2018-10-21 13:10 UTC

**Comment by dongsiji** [comment] 2018-10-21 13:17
Didn't notice #549 thanks.
