### ISSUE TITLE
Defining a function without the keyword `function` highlights its identifier as unknown/error

### ISSUE THREAD

**Issue by Iskustvo** [zsh-users/zsh-syntax-highlighting#891] opened 2022-08-14 20:56 UTC
Steps to reproduce:
* Start the zsh in new terminal emulator, without any configuration
  ```zsh
  termite -e 'zsh -dfi'
  ```
* Source z-sy-h from where it's installed, and use only `main` highlighter
  ```zsh
  source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)
  ```
* Compare the highlighting of the function identifier with and without preceding keyword `function`
  ![2022-08-14-225152_1920x1080_scrot](https://user-images.githubusercontent.com/23140889/184554565-50b13bd4-f568-44fd-8862-dda50479d47c.png)
  ![2022-08-14-225318_1920x1080_scrot](https://user-images.githubusercontent.com/23140889/184554566-7297af81-67dc-488c-b0ac-46aa1645d813.png)

Versions:
``` 
zsh - 5.9-1
zsh-syntax-highlighting - 0.7.1-1
```

**Comment by danielshahaf** [comment] 2022-08-19 09:33
Duplicate of https://github.com/zsh-users/zsh-syntax-highlighting/issues/223.  (Though to be fair, I remembered that issue was labeled needs:lookahead, so it was easy for me to find it.)

**Comment by Iskustvo** [comment] 2022-08-20 22:01
> Duplicate of #223. (Though to be fair, I remembered that issue was labeled needs:lookahead, so it was easy for me to find it.)

Fair enough. Why not close this one then?

**Closed** 2022-09-24 00:57 UTC
