### ISSUE TITLE
ctrl-W and ctrl-Y behaviour is broken

### ISSUE THREAD

**Issue by Elronnd** [zsh-users/zsh-syntax-highlighting#597] opened 2018-12-30 21:43 UTC
In normal zsh, if I've typed `$ a b` and then ^W^W^Y, I'll end up with the same command-line -- `$ a b`.  With this addon, though, the ^W only captures the a, so I end up with `$ a`.

**Comment by danielshahaf** [comment] 2018-12-31 10:48
Duplicate of #150, already fixed on the `feature/redrawhook` branch.

**Closed by danielshahaf** 2018-12-31 10:48 UTC
