### ISSUE TITLE
command is red after sudo work

### ISSUE THREAD

**Issue by Ruochenfu2011** [zsh-users/zsh-syntax-highlighting#882] opened 2022-07-01 05:24 UTC
Like if you do
alias rm="This\ Command\ is\ Deleted"

and you type sudo rm, because that that i didn't use alias -g, so that i actually can use sudo rm, but it's shown red

**Comment by phy1729** [comment] 2022-07-04 03:22
Duplicate of #608.

**Closed by phy1729** 2022-07-04 03:22 UTC
