### ISSUE TITLE
Called without argument

### ISSUE THREAD

**Issue by naquiroz** [zsh-users/zsh-syntax-highlighting#549] opened 2018-10-13 04:24 UTC
I'm using `oh-my-zsh` with syntax highlighting, and every time you type an alias '..' to go back, you get

```
.zsh-syntax-highlighting: BUG: _zsh_highlight_main_highlighter_expand_path: called without argument
```

**Comment by phy1729** [comment] 2018-10-13 13:00
I think this was recently fixed in 07f259f. Could you update to current master and try to reproduce?
If it still happens, could you come up with a minimal reproducer: starting with zsh -f and sourcing zsh-syntax-highlighting.zsh and the minimal required config to reproduce the bug.

**Comment by bronxct1** [comment] 2018-10-17 15:35
I'm having this same issue when using `...` with oh my zsh. Is there anything I can provide to help locate the issue?

**Comment by rhuang2014** [comment] 2018-10-17 19:30
I resolved my issue with the change below.

```
diff --git a/highlighters/main/main-highlighter.zsh b/highlighters/main/main-highlighter.zsh
index 455c21f..a486229 100644
--- a/highlighters/main/main-highlighter.zsh
+++ b/highlighters/main/main-highlighter.zsh
@@ -523,7 +523,7 @@ _zsh_highlight_main_highlighter_highlight_list()
             _zsh_highlight_main__type "$arg"
           done
         }
-        _zsh_highlight_main_highlighter_expand_path $arg
+        _zsh_highlight_main_highlighter_expand_path "$arg"
         arg=$REPLY
         () {
           # Make sure to use $arg_raw here, rather than $arg.
@@ -554,7 +554,7 @@ _zsh_highlight_main_highlighter_highlight_list()
           fi
         }
       else
-        _zsh_highlight_main_highlighter_expand_path $arg
+        _zsh_highlight_main_highlighter_expand_path "$arg"
         arg=$REPLY
         _zsh_highlight_main__type "$arg"
         res="$REPLY"
```

**Comment by phy1729** [comment] 2018-10-18 03:51
Can someone share what you have to type to trigger this along with any related config? A minimal reproducer could be added to the test suite to ensure this issue doesn't resurface. I'd also like to understand how the issue arises.

**Comment by danielshahaf** [comment] 2018-10-18 23:31
@phy1729 `alias x=''` then `x` in command word position.

**Comment by danielshahaf** [comment] 2018-10-18 23:56
Actually, in this situation we should add `x` to `precommand_options`.

**Comment by phy1729** [comment] 2018-10-19 03:03
#556 Fixes the `alias x=''` issue because it will elide the null argument. No need to much with `precommand_options`.

**Comment by mustafaturksavas** [comment] 2018-10-20 19:01
When I try to use ... instead to go two folders up, I get this:

`..zsh-syntax-highlighting: BUG: _zsh_highlight_main_highlighter_expand_path: called without argument`

I'm on a Mac using `oh-my-zsh` and I have the plugins: `git`, `z`, `OSX` and `zsh-syntax-highlighting` activated. I'm using the most recent version of `zsh-syntax-highlighting`.

**Comment by danielshahaf** [comment] 2018-10-20 20:46
@mustafaturksavas @bronxct1 Could one of you share the defnition of `...` please? Run `alias -L '...'; which '...'; type '...'`, one of them should do it.

**Comment by mustafaturksavas** [comment] 2018-10-20 21:00
@danielshahaf 
`alias -g ...=../..`

**Comment by phy1729** [comment] 2018-10-21 02:39
Can this still be reproduced now that #556 is merged?

**Comment by mustafaturksavas** [comment] 2018-10-21 11:00
> Can this still be reproduced now that #556 is merged?

Fixed the issue for me. Thanks for the fix @danielshahaf @phy1729

**Comment by naquiroz** [comment] 2018-10-21 16:03
Issue fixed! Thanks!

**Comment by phy1729** [comment] 2018-10-21 17:14
Thanks for checking!

**Closed by phy1729** 2018-10-21 17:14 UTC
Labels: Bug, syntax:command-word

**Comment by rhuang2014** [comment] 2018-10-21 17:40
Issue fixed for me as well. thanks.
