### ISSUE TITLE
zsh crashes when doing multi-line editing

### ISSUE THREAD

**Issue by toffaletti** [zsh-users/zsh-syntax-highlighting#108] opened 2013-02-27 22:16 UTC
```
$ echo "
fdsfsdfds
fdsfsdfdsfs
fdsfsdfsdfsd
fdsfsdfsdfs
```

Just keep doing this and zsh will eventually crash but only when syntax highlighting is enabled.

**Comment by fievelk** [comment] 2015-06-23 12:15
Is there a solution for this?

**Comment by danielshahaf** [comment] 2015-06-24 13:33
I haven't attempted to reproduce this issue, but if you see a segfault, then there is a bug in zsh itself. (There may or may not be a bug in zsh-syntax-highlighting, but nothing it does should cause a segfault, and it doesn't contain any C code of its own.)

It should be possible to reproduce the segfault in vanilla zsh without zsh-syntax-highlighting.

**Comment by danielshahaf** [comment] 2015-09-01 17:32
I cannot reproduce this with zsh-5.0.7 or zsh-5.1. Since the duplicate issue #141 provided a very clear and unambiguous recipe, I'll go ahead and close this as an upstream bug that is presumed to have been fixed. Please reopen if you can reproduce this with a new zsh.

**Closed by danielshahaf** 2015-09-01 17:32 UTC
Labels: Bug
